### ISSUE TITLE
->each returns DOMElement instead of DomQuery

### ISSUE THREAD

**Issue by torian257x** [Rct567/DomQuery#13]
is that on purpose?

e.g. I cannot do

```
$dq->find('select[name="myname"]')->each(function ($el, $i){
            /** @var \DOMElement $el */
            $linktag = $el->parent(); //meeep parent doesn't exist on DOMElement

});
```

**Comment by Rct567** [comment]
Yeh it is, see also: https://api.jquery.com/each/

If you want the result as an DomQuery instance you can just use a _foreach_ loop.

**Comment by torian257x** [comment]
@Rct567 ahh thanks
well in jquery you can do

```
->each(function(el){
var jel = $(el);
jel.parent();
});
```

is there something equivalent?

**Comment by Rct567** [comment]
The constructor also accepts DOMNode/DOMElement, so just use `new DomQuery` (or `DomQuery::create`)  instead of `$` 😁
