### ISSUE TITLE
Odd new issue: "Uncaught Exception"

### ISSUE THREAD

**Issue by msitarzewski** [Rct567/DomQuery#15]
I've been using DomQuery for some time, and recently (I'm not sure how recent) this exception reared its head. It looks like it has to do with CSSS selector to Xpath conversion. The original selector was:  "ul.specifications li:nth-child(1)"

It seems to happen on every text I submit as a CSS selector.

PHP Fatal error:  Uncaught Exception: Expression //ul[contains(concat(' ', normalize-space(@class), ' '), ' specifications ')]/li:nth-child(1) is malformed. in /var/www/ig/common/ext/vendor/rct567/dom-query/src/Rct567/DomQuery/DomQueryNodes.php:661

Thank you!

**Comment by Rct567** [comment]
Sorry for the late response. I'm closing this issue as I can't replicate this issue on the most recent version. Feel free to resubmit this issue if you still encounter this error.
