### ISSUE TITLE
Select Class Error

### ISSUE THREAD

**Issue by SpyShare** [Rct567/DomQuery#17]
im try select Class But Get Error My Code:
  
```

require '../../Phper/Slcquery/vendor/autoload.php';
use Rct567\DomQuery\DomQuery;

$resp = "<div class='Test'> <a> Hello World </a> </div>";
 
    $dom = new DomQuery("<div>".$resp."</div>");

     $links = $dom->find('.Test');

     echo $links->html(); 
 
```
**Fatal error: Uncaught Exception: Expression //.Test is malformed. in D:\Xampp\htdocs**

**Comment by Rct567** [comment]
Please try the latest version and let me know if you still encounter this issue.
