### ISSUE TITLE
Support PHP 5.6?

### ISSUE THREAD

**Issue by trananhmanh89** [Rct567/DomQuery#3]
Your works are awesome. Thanks!

One thing i want to ask. 

Could you make DomQuery run on PHP 5.6?

I use it to build a joomla extension, and users are using php 5.6 alot.
I can make a PR if you want, just a few syntax error.

**Comment by ghost** [comment]
phpQuery-0.9.5 @trananhmanh89

**Comment by Rct567** [comment]
Unfortunately there are no plans to add support for PHP5. This is mainly because it would require more work (on a continues basis) than just fixing some syntax errors.
