### ISSUE TITLE
Expression //.🐝apo is malformed.

### ISSUE THREAD

**Issue by jslim89** [Rct567/DomQuery#4]
I was trying to read the classname with emoji, but then I get that error _(as mentioned in title)_.

[This is the site I trying to read](https://www.honestbee.my/en/groceries/stores/bens-independent-grocer/products/720365). I tried with jQuery and it works fine.

```js
$('.🐝ap0 .🐝0k').text(); // output RM 13.10
```

Is there any way to do with this DomQuery?

**Comment by jslim89** [comment]
@Rct567 Thank you so much. It works now. But why the version in [packagist (dd17eae)](https://packagist.org/packages/rct567/dom-query) not up-to-date?

**Comment by Rct567** [comment]
I just released a new version :) 

Don't know why, but I had to manually update on packagist.org itself to get the new version there.

**Comment by jslim89** [comment]
I see. Thank you very much 😁
